apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-agent
  namespace: drone
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-agent
    spec:
      containers:
      - image: drone/agent:0.8
        imagePullPolicy: Always
        name: drone-agent
        volumeMounts:
          # Enables Docker in Docker
          - name: docker-socket
            mountPath: /var/run/docker.sock
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: DRONE_SERVER
          value: drone-service:9000
        - name: DRONE_HEALTHCHECK
          value: "true"
        # issue: https://github.com/drone/drone/issues/2048
        - name: DOCKER_API_VERSION
          value: "1.24"
        - name: DRONE_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-secrets
              key: server.secret
        - name: DRONE_MAX_PROCS
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: agent.max.procs
        - name: DRONE_DEBUG
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: agent.debug
        - name: DRONE_DEBUG_PRETTY
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: agent.debug.pretty
        - name: DRONE_HEALTHCHECK
          valueFrom:
            configMapKeyRef:
              name: drone-config
              key: agent.healthcheck

      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
